human_pose/human_pose_2d:
  ros__parameters:
    keypoint_name_list:
      - "nose"
      - "neck"
      - "right_shoulder"
      - "right_elbow"
      - "right_wrist"
      - "left_shoulder"
      - "left_elbow"
      - "left_wrist"
      - "right_hip"
      - "right_knee"
      - "right_ankle"
      - "left_hip"
      - "left_knee"
      - "left_ankle"
      - "right_eye"
      - "left_eye"
      - "right_ear"
      - "left_ear"
      # - "nose"
      # - "neck"
      # - "r_sho"
      # - "r_elb"
      # - "r_wri"
      # - "l_sho"
      # - "l_elb"
      # - "l_wri"
      # - "r_hip"
      # - "r_knee"
      # - "r_ank"
      # - "l_hip"
      # - "l_knee"
      # - "l_ank"
      # - "r_eye"
      # - "l_eye"
      # - "r_ear"
      # - "l_ear"